"""

Revision ID: 0dbc871a6cc4
Revises: e60044dc9634
Create Date: 2026-05-13 17:37:42.038878

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0dbc871a6cc4'
down_revision: Union[str, Sequence[str], None] = 'e60044dc9634'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('creator_id', sa.Uuid(), nullable=False))
    op.create_foreign_key(None, 'articles', 'users', ['creator_id'], ['id'])
    op.drop_constraint(op.f('reviews_status_fkey'), 'reviews', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('reviews_status_fkey'), 'reviews', 'review_statuses', ['status'], ['name'])
    op.drop_constraint(None, 'articles', type_='foreignkey')
    op.drop_column('articles', 'creator_id')
    # ### end Alembic commands ###
