"""

Revision ID: 6fb0f9ea646f
Revises: 0dbc871a6cc4
Create Date: 2026-05-15 20:32:13.050534

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6fb0f9ea646f'
down_revision: Union[str, Sequence[str], None] = '0dbc871a6cc4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('is_visible', sa.Boolean(), nullable=False))
    op.add_column('citations', sa.Column('doi', sa.String(length=255), nullable=True))
    op.add_column('citations', sa.Column('raw_reference', sa.Text(), nullable=True))
    op.add_column('citations', sa.Column('match_status', sa.String(length=20), nullable=False))
    op.alter_column('citations', 'to_article_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(op.f('citations_to_article_id_fkey'), 'citations', type_='foreignkey')
    op.create_foreign_key(None, 'citations', 'articles', ['to_article_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'citations', type_='foreignkey')
    op.create_foreign_key(op.f('citations_to_article_id_fkey'), 'citations', 'articles', ['to_article_id'], ['id'], ondelete='CASCADE')
    op.alter_column('citations', 'to_article_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('citations', 'match_status')
    op.drop_column('citations', 'raw_reference')
    op.drop_column('citations', 'doi')
    op.drop_column('articles', 'is_visible')
    # ### end Alembic commands ###
