"""

Revision ID: c8d6eb10e6b5
Revises: 6fb0f9ea646f
Create Date: 2026-05-16 15:37:13.945252

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c8d6eb10e6b5'
down_revision: Union[str, Sequence[str], None] = '6fb0f9ea646f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('article_versions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('article_id', sa.Uuid(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('abstract', sa.Text(), nullable=True),
    sa.Column('keywords', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('language', sa.VARCHAR(length=5), nullable=False),
    sa.Column('pdf_path', sa.String(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('updated_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['status'], ['article_statuses.name'], ),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('article_id', 'version_number', name='uq_article_version')
    )
    op.create_table('review_assignments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('article_version_id', sa.Uuid(), nullable=False),
    sa.Column('reviewer_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['article_version_id'], ['article_versions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('article_version_id')
    )
    op.create_table('version_comments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('article_version_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['article_version_id'], ['article_versions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('article_approvals', sa.Column('article_version_id', sa.Uuid(), nullable=False))
    op.drop_constraint(op.f('article_approvals_article_id_fkey'), 'article_approvals', type_='foreignkey')
    op.create_foreign_key(None, 'article_approvals', 'article_versions', ['article_version_id'], ['id'], ondelete='CASCADE')
    op.drop_column('article_approvals', 'article_id')
    op.add_column('articles', sa.Column('current_version_id', sa.Uuid(), nullable=True))
    op.drop_constraint(op.f('articles_status_fkey'), 'articles', type_='foreignkey')
    op.drop_constraint(op.f('articles_updated_by_user_id_fkey'), 'articles', type_='foreignkey')
    op.create_foreign_key(None, 'articles', 'article_versions', ['current_version_id'], ['id'])
    op.drop_column('articles', 'abstract')
    op.drop_column('articles', 'status')
    op.drop_column('articles', 'updated_by_user_id')
    op.drop_column('articles', 'keywords')
    op.drop_column('articles', 'title')
    op.drop_column('articles', 'pdf_path')
    op.drop_column('articles', 'language')
    op.drop_column('articles', 'published_at')
    op.drop_column('articles', 'updated_at')
    op.add_column('reviews', sa.Column('review_assignment_id', sa.Uuid(), nullable=False))
    op.create_unique_constraint(None, 'reviews', ['review_assignment_id'])
    op.drop_constraint(op.f('reviews_reviewer_id_fkey'), 'reviews', type_='foreignkey')
    op.drop_constraint(op.f('reviews_article_id_fkey'), 'reviews', type_='foreignkey')
    op.create_foreign_key(None, 'reviews', 'review_assignments', ['review_assignment_id'], ['id'], ondelete='CASCADE')
    op.drop_column('reviews', 'comment')
    op.drop_column('reviews', 'article_id')
    op.drop_column('reviews', 'reviewer_id')
    op.drop_column('reviews', 'updated_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('reviews', sa.Column('reviewer_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('reviews', sa.Column('article_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('reviews', sa.Column('comment', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'reviews', type_='foreignkey')
    op.create_foreign_key(op.f('reviews_article_id_fkey'), 'reviews', 'articles', ['article_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('reviews_reviewer_id_fkey'), 'reviews', 'users', ['reviewer_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'reviews', type_='unique')
    op.drop_column('reviews', 'review_assignment_id')
    op.add_column('articles', sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('articles', sa.Column('published_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('articles', sa.Column('language', sa.VARCHAR(length=5), autoincrement=False, nullable=False))
    op.add_column('articles', sa.Column('pdf_path', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('articles', sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('articles', sa.Column('keywords', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True))
    op.add_column('articles', sa.Column('updated_by_user_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('articles', sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'DRAFT'::character varying"), autoincrement=False, nullable=False))
    op.add_column('articles', sa.Column('abstract', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'articles', type_='foreignkey')
    op.create_foreign_key(op.f('articles_updated_by_user_id_fkey'), 'articles', 'users', ['updated_by_user_id'], ['id'])
    op.create_foreign_key(op.f('articles_status_fkey'), 'articles', 'article_statuses', ['status'], ['name'])
    op.drop_column('articles', 'current_version_id')
    op.add_column('article_approvals', sa.Column('article_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'article_approvals', type_='foreignkey')
    op.create_foreign_key(op.f('article_approvals_article_id_fkey'), 'article_approvals', 'articles', ['article_id'], ['id'], ondelete='CASCADE')
    op.drop_column('article_approvals', 'article_version_id')
    op.drop_table('version_comments')
    op.drop_table('review_assignments')
    op.drop_table('article_versions')
    # ### end Alembic commands ###
